#!/usr/bin/env python3
"""Generate src/edition4.rs from XML 1.0 (Fourth Edition), Appendix B.

Reads productions [85] BaseChar, [86] Ideographic, [87] CombiningChar,
[88] Digit and [89] Extender straight out of the W3C Recommendation and
emits them as sorted Rust range tables. Do not edit src/edition4.rs by
hand -- rerun this instead:

    python3 tools/gen_edition4_tables.py > src/edition4.rs

An optional argument names a local copy of the spec HTML; otherwise it is
fetched from SPEC_URL.
"""
import html
import re
import sys
import urllib.request

SPEC_URL = "https://www.w3.org/TR/2006/REC-xml-20060816/"
PRODUCTIONS = [
    (85, "BaseChar", "BASE_CHAR"),
    (86, "Ideographic", "IDEOGRAPHIC"),
    (87, "CombiningChar", "COMBINING_CHAR"),
    (88, "Digit", "DIGIT"),
    (89, "Extender", "EXTENDER"),
]


def load_spec():
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as f:
            return f.read()
    with urllib.request.urlopen(SPEC_URL) as r:
        return r.read().decode("utf-8")


def production_rhs(spec, name):
    """Text of the right-hand side of production `name` (tags stripped)."""
    m = re.search(r'id="NT-%s".*?::=.*?<code>(.*?)</code>' % name, spec, re.S)
    if not m:
        sys.exit(f"production {name} not found in spec")
    return html.unescape(re.sub(r"<[^>]+>", "", m.group(1)))


def parse_ranges(rhs):
    ranges = []
    for alt in rhs.split("|"):
        alt = alt.strip()
        m = re.fullmatch(r"\[#x([0-9A-Fa-f]+)-#x([0-9A-Fa-f]+)\]", alt)
        if m:
            ranges.append((int(m.group(1), 16), int(m.group(2), 16)))
            continue
        m = re.fullmatch(r"#x([0-9A-Fa-f]+)", alt)
        if m:
            n = int(m.group(1), 16)
            ranges.append((n, n))
            continue
        sys.exit(f"unrecognised alternative {alt!r}")
    ranges.sort()
    for (a, b), (c, _) in zip(ranges, ranges[1:]):
        if c <= b:
            sys.exit(f"overlapping ranges {a:#x}-{b:#x} / {c:#x}")
    return ranges


def main():
    spec = load_spec()
    out = [
        "//! XML 1.0 (Fourth Edition) Appendix B character classes.",
        "//!",
        "//! GENERATED by tools/gen_edition4_tables.py from",
        f"//! <{SPEC_URL}> -- do not edit by hand.",
        "",
    ]
    for num, name, const in PRODUCTIONS:
        ranges = parse_ranges(production_rhs(spec, name))
        out.append(f"/// [{num}] {name} -- {len(ranges)} ranges.")
        out.append(f"pub(crate) const {const}: &[(char, char)] = &[")
        for a, b in ranges:
            out.append(f"    ('\\u{{{a:04X}}}', '\\u{{{b:04X}}}'),")
        out.append("];")
        out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
